split:
  test_size: 0.2
  random_state: 0

gridsearch:
  cv: 3
  scoring: neg_mean_squared_error
  param_grid:
    n_estimators: [20,50,100, 200, 300]
    max_depth: [2, 3, 5, 7]
    learning_rate: [0.001, 0.01, 0.05, 0.1]